grafana:
        image: grafana/grafana
        ports: 
        - "3000:3000"
        environment:
            - GF_SERVER_ROOT_URL=http://grafana.specialite-de-france.tk
            - GF_SECURITY_ADMIN_PASSWORD=passroot
        volumes:
            - grafanadb:/var/lib/grafana
            - ./grafana/var/lib/:/var/lib/grafana
            - ./grafana/var/lib/plugins/:/var/lib/grafana/plugins
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
            - elk-data:/usr/share/elasticsearch/data
    ports:
            - "9200:9200"

logstash:
    image: docker.elastic.co/logstash/logstash:5.5.0
    environment:
    # This helps Logstash out if it gets too busy
    - LS_HEAP_SIZE=2048m
    volumes:
    # volume mount the logstash config
    - ./logstash/conf.d/:/usr/share/logstash/pipeline/
    - ./logstash/logstash.yml:/opt/logstash/config/logstash.yml
    - ./logstash/GeoLite2-City.mmdb:/opt/logstash/GeoLite2-City.mmdb
    ports:
    - "5140:5140"
    - "5140:5140/udp"
    - "5044:5044"
    links:
    - elasticsearch

kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    links:
            - elasticsearch
    ports:
            - "5601:5601"

influxdb:
        image: influxdb
        ports:
        - "8086:8086"
        volumes:
        - influxdb:/var/lib/influxdb
        - ./influxdb/var/lib/influxdb:/var/lib/influxdb

parsoid:
        image: centos
        ports:
                - "8000:8000"
                - "8142:8142" 
